"""Constants for the GA
    """

MAX_BUILDING_RADIUS = 20
MIN_BUILDING_RADIUS = 10
WATER_DISTANCE_WEIGHTING = 1.75
BUILDING_DISTANCE_WEIGHTING = 1.5
FLATNESS_FITNESS_WEIGHTING = 1
DEFAULT_MUTATION_RATE = 1 / 3
DEFAULT_POPULATION_SIZE = 5
GENERATIONS = 20
BUILDING_NUMBER = 5
POPULATION_SIZE = 5
AREA = (0, 0, 256, 256)  # x position, z position, x size, z size
